### PR TITLE
Add reason and headers

### PR DESCRIPTION
**Pull request by bessone**
When reading the redirect chain I needed more details such as headers.

Since Guzzle already manages the reason (so as to explain the status code) and the headers of each request, I made a small change to the middleware to add this information.

They could be useful to others, they are not blockers, I thought about doing the PR.

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks!

**Comment by freekmurze** [comment]
It seems that the tests were not updated. Could you send another PR to fix them? When the tests are green again, I'll tag a new release.

**Comment by bessone** [comment]
The failure of the test seems to me not related to my code but to the missing dependency, if I update with the composer.json that you have modified should it be enough?

**Comment by freekmurze** [comment]
Looking at the output of the tests, it seems that the test don't account for new things you added in this PR: https://github.com/spatie/guzzle-redirect-history-middleware/runs/8014332138?check_suite_focus=true#step:6:69

**Comment by bessone** [comment]
Thanks for your help, I'm working on it

**Comment by bessone** [comment]
I have a problem with the test, in the data to be compared there is the date, which obviously is different at each run.

You who are a true PEST expert can you give me a tip on how to manage it?

A piece of my code:
```php
    expect($this->redirectHistory->toArray())->toBeArray()->toMatchArray([
        [
            'status' => 302,
            'url' => 'https://ohdear.app/test-routes/redirect/number/2',
            'reason' => 'Found',
             'headers' => [
                 'Server' => ['nginx/1.17.3'],
                 'Content-Type' => ['text/html; charset=UTF-8'],
                 'Transfer-Encoding' => ['chunked'],
                 'Connection' => ['keep-alive'],
                 'Cache-Control' => ['no-cache, private'],
                 'Date' => ['Thu, 25 Aug 2022 14:01:09 GMT'],
                 'Location' => ['https://ohdear.app/test-routes/redirect/number/1'],
                 'X-Frame-Options' => ['SAMEORIGIN'],
                 'X-XSS-Protection' => ['1; mode=block'],
                 'X-Content-Type-Options' => ['nosniff'],
             ]
        ],
        [
            'status' => 302,
            'url' => 'https://ohdear.app/test-routes/redirect/number/1',
            'reason' => 'Found',
            'headers' => [
                'Server' => ['nginx/1.17.3'],
                'Content-Type' => ['text/html; charset=UTF-8'],
                'Transfer-Encoding' => ['chunked'],
                'Connection' => ['keep-alive'],
                'Cache-Control' => ['no-cache, private'],
                'Date' => ['Thu, 25 Aug 2022 14:01:09 GMT'],
                'Location' => ['https://ohdear.app/test-routes/redirect/number/0'],
                'X-Frame-Options' => ['SAMEORIGIN'],
                'X-XSS-Protection' => ['1; mode=block'],
                'X-Content-Type-Options' => ['nosniff']
            ]
        ],
        [
            'status' => 204,
            'url' => 'https://ohdear.app/test-routes/redirect/number/0',
            'reason' => 'No Content',
            'headers' => [
                'Server' => ['nginx/1.17.3'],
                'Connection' => ['keep-alive'],
                'Cache-Control' => ['no-cache, private'],
                'Date' => ['Thu, 25 Aug 2022 14:01:09 GMT'],
                'X-Frame-Options' => ['SAMEORIGIN'],
                'X-XSS-Protection' => ['1; mode=block'],
                'X-Content-Type-Options' => ['nosniff']
            ]
        ],
    ]);
```

Is it possible to manage the validation of the date or exclude it in some way?

**Comment by freekmurze** [comment]
Take a look at the time plugin which can freeze the time: https://pestphp.com/docs/plugins/time

**Pull request merged**
